### ISSUE TITLE
Merging `DofHandler` and `MixedDofHandler`

### ISSUE THREAD

**Issue by fredrikekre** [Ferrite-FEM/Ferrite.jl#624]
### Background

Ferrite.jl has, for quite some time, maintained two different DoF handlers: the original `DofHandler` and the `MixedDofHandler`. The `DofHandler` is limited to i) single element type (e.g. only triangles, or only quads) and ii) to uniform dof distribution (e.g. all fields live on all elements). `MixedDofHandler` enables both these use cases, so functionality-wise it it is a superset of `DofHandler`. Naturally it would be good to only have a single DoF handler instead of maintaining two.

Performance wise the `DofHandler` is generally better, since it doesn't have to deal with the `Union` element type (when combining different elements). A lot of work, mainly by @kimauth has been done to reduce the performance gap, and I think that we are now at a point where we can merge them into a new DoF handler that can support all usecases with good performance.

### `DofHandler`

```julia
dh = DofHandler(grid)
add!(dh, :u, 2, u_interp)
```

### `NewDofHandler`

Initially the plan was to simply remove `DofHandler` and then rename `MixedDofHandler` to `DofHandler`. However, while we 

### Implementation plan
 - [ ] "Fork" `NewDofHandler` from `MixedDofHandler`
 - [ ] Update `NewDofHandler` to new common interface
 - [ ] Compare and test performance and functionality between `NewDofHandler` and `DofHandler`/`MixedDofHandler`
 - [ ] Delete `DofHandler` and `MixedDofHandler`, rename `NewDofHandler` to `DofHandler`.

**Comment by fredrikekre** [comment]
Okay, now you may read.

**Comment by lijas** [comment]
Regarding the name `FieldHandler`. Maybe `DofRegion`, `CellGroup`, `Region` or similar could work? If we rename it `SubDofHandler`, it sounds like it has the same complexity and functionality as the `DofHandler`, like distributing dofs, keeping track of celldofs etc (which it cant).

I like the idea of pushing seperate fields to the "`SubDofHandler`"  though.

**Comment by fredrikekre** [comment]
> keeping track of celldofs etc (which it cant).

I was thinking it should do this though, and would enable cell iteration over the subdofhandler directly, with all the same queries as you can do on the standard dofhandler.

**Comment by lijas** [comment]
> I was thinking it should do this though, and would enable cell iteration over the subdofhandler directly, with all the same queries as you can do on the standard dofhandler.

Hmm, I dont see very much benefit with this I think :thinking:  . The way we do it now feels more clear/direct:

```
for c in CellIterator(dh, cellset)
    # use dofhandler directly
end
```

**Comment by fredrikekre** [comment]
1. Maybe, but then I think we still need to partitione the domain based on the input, instead of asking the user to tell it explicitly. E.g., imagine if you do
   ```julia
   add!(dh, :u, 3) # all cells
   add!(dh, :p, 1, somesubdomain)
   ```
   then I think we would need to split the `:u` part into `subsubdomain` and `fulldomain - subdomain` to simplify things. In addition, at least for the usecase of multiple element types, you would need different interpolations anyway. Migth not be worth having this shortcut for the case of uniform element type and different fields on different regions.

2. I wasn't thinking to make `SubDofHandler <: AbstractDofHandler`, but maybe it would simplify things. Otherwise I don't understand why the name matters for the dispatch.
3. I don't understand the question, advantage over what?
4. (+ Elias comment). That probably works just fine, but there is no guarantee what celltype is included in that cellset, and you would still need to send around that cellset instead of a subdofhandler. My thinking was that we have
   ```
   struct SubDofHandler{CT}
       dh::DofHandler
       cellset::Set{Int}
   end
   ```
   where we can compute `CT` at construction (since each subdomain is required to have a concrete type, already now). Then we now that when iterating over a `SubDofHandler` is must return elements of type `CT`.

**Comment by koehlerson** [comment]
>     4. (+ Elias comment). That probably works just fine, but there is no guarantee what celltype is included in that cellset, and you would still need to send around that cellset instead of a subdofhandler. My thinking was that we have
>        ```
>        struct SubDofHandler{CT}
>            dh::DofHandler
>            cellset::Set{Int}
>        end
>        ```
>        where we can compute `CT` at construction (since each subdomain is required to have a concrete type, already now). Then we now that when iterating over a `SubDofHandler` is must return elements of type `CT`.


I'd vote for this as well

**Comment by KnutAM** [comment]
Very nice to see this progress!
Regarding the "Implementation plan", I would prefer to make the change in one release at least to avoid having to update dependent libraries twice. 

> `dh = NewDofHandler(sdh1, sdh2, ..)`

This would be very nice and we could even allow `dh = NewDofHandler(grid, fieldname, dim)` as a one-liner setup for a single-field case:)
For setting up, we could also have a `FieldDomain` which is only used for setting up the `NewDofHandler`,
```julia
struct FieldDomain
 cellset::Set{Int}
 fields::Vector{Field}
end
```
where in `Field` the interpolation field is changed to `Union{Interpolation,Nothing}` (where `nothing` implies using the default interpolation). Then, upon calling `dh = NewDofHandler(grid, fd1, fd2, ...)` to create and close the `NewDofHandler`, which contains `SubDofHandlers` that are created based on the `FieldDomain`s. 
This way, the `NewDofHandler` and the `SubDofHandlers` can be better typed, e.g. the number of `SubDofHandlers` (same as above), but also the specific interpolations for each `SubDofHandler`.

**Comment by termi-official** [comment]
Implementing the one liner is already possible with something along these lines:
```
function DofHandler(grid, fieldname, dim)
    dh = DofHandler(grid)
    ip = default_interpolation(getcelltype(dh.grid))
    add!(dh, fieldname, dim, ip)
    close!(dh)
    return dh
end
```
where we should be able to do something similar for the `MixedDofHandler` by iterating over the cell types in the grid and adding the default interpolations individually.


@fredrikekre Assuming your `SubDofHandler` design. Let us take for example a grid with 3 elements, where the we add the field :u1 to element 1, then :u2 to elements 1,2,3 and finally :u3 to element 3. Any idea how to make a functional `dof_range` that is not too expensive? This case should show that, assuming that we allow overlapping subdomains as suggested above, then in the worst case `dof_range` needs to be computed per element.

**Comment by KnutAM** [comment]
> Implementing the one liner is already possible with something along these lines:

Yes, even simpler: `DofHandler(grid::Grid, fieldname::Symbol, dim::Int) = (dh=DofHandler(grid); add!(dh, fieldname, dim); close!(dh))` :) 

> Let us take for example a grid with 3 elements, where the we add the field :u1 to element 1, then :u2 to elements 1,2,3 and finally :u3 to element 3.

But you wouldn't do that or? With the current mixed dof handler (and as I understand the same with the new): 
you would do 
```julia
set1 = Set(1); set2 = Set(2); set3=Set(3); 
dh = NewDofHandler(grid)
sdh1 = SubDofHandler(dh, set1)
add!(sdh1, :u1)
add!(sdh1, :u3)
sdh2 = SubDofHandler(dh, set2)
add!(sdh2, :u1)
add!(sdh2, :u3)
sdh3 = SubDofHandler(dh, set3)
add!(sdh3, :u3)
close!(dh)
```

**Comment by termi-official** [comment]
Indeed. :)

**Comment by kimauth** [comment]
The subdofhandler design is in fact what the `MixedDofHandler` does already, with the `FieldHandler`s representing the subdomains. An important point is that the cellsets must be disjoint, as [documented](https://ferrite-fem.github.io/Ferrite.jl/stable/reference/dofhandler/#Ferrite.FieldHandler). This is also checked during construction. This results in one `dof_range` per `Fieldhandler` for each field. You can cache them, they will never change after constructing the `MixedDofHandler`, but they're also not that expensive to compute since #621.
So your example is possible already @termi-official, it would look similar to what the first post shows. (And a point here is to find nicer syntax for it.)

**Comment by termi-official** [comment]
I see. Just as you wrote I also discovered the related code (but really missed the docs). I totally misunderstood Fredrik's answer, but now it makes sense. Thanks for elaborating on this Kim! This also explains my third question above, why we should have multiple fields per `FieldHandler` (or whatever we want to call it) in this design.

**Comment by termi-official** [comment]
#627 adds feature parity between the DofHandlers for high order dof distribution.
